//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABDUBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanalPosMusteri
    {
        public int ID { get; set; }
        public string Isim { get; set; }
        public string SaticiNo { get; set; }
        public string SaticiSifre { get; set; }
        public decimal Bakiye { get; set; }
        public bool Durum { get; set; }
    }
}
